spring.application.name=fleet-management-system
spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_management
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false